name: "trigger ci / cd steps"
on:
  issue_comment:
    types: [created]
jobs:
  cicdsteps:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: |
          deno --version
          deno run --allow-net https://deno.land/x/cicd/post-PR-checklist.ts
          deno run --allow-net https://deno.land/x/cicd/lint.ts
          # deno run --allow-net https://deno.land/x/cicd/security-scan.ts
          # deno run --allow-net https://deno.land/x/cicd/request-cla-signature.ts
          # deno run --allow-net https://deno.land/x/cicd/request-dco-signature.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-telegram.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-slack.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-discord.ts          
          # deno run --allow-net https://deno.land/x/cicd/publish-on-nest.land.ts          
          # deno run --allow-net https://deno.land/x/cicd/create-patch-release.ts                    
          # deno run --allow-net https://deno.land/x/cicd/create-minor-release.ts                    
          # deno run --allow-net https://deno.land/x/cicd/create-major-release.ts                                        
